// Filament database for Filament Wizard
// - pricePerKg: rough average retail price per kg (adjust for your local reality).
// - toxicity: relative only (not medical advice):
//   "very_low", "low", "medium", "high", "very_high"

const FILAMENTS = [
  // =========================
  // STANDARD / EVERYDAY
  // =========================

  {
    id: "pla",
    name: "PLA",
    category: "standard",
    strength: "medium",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "easy",
    weight: "normal",
    special: [],
    pricePerKg: 22,
    toxicity: "low",
    useCases: "Miniatures, prototypes, terrain, cosplay props, general decorative parts.",
    pros: "Very easy to print, low warp, good detail and surface quality, widely available, inexpensive.",
    cons: "Low heat resistance, can deform in hot cars, can be brittle, poor long-term outdoor performance.",
    nozzle: "200–215°C",
    bed: "50–60°C",
    speed: "200–300 mm/s",
    adhesion: "Usually none needed on textured / cool plates.",
    enclosure: "open_ok"
  },

  {
    id: "pla_plus",
    name: "PLA+",
    category: "standard",
    strength: "medium",
    flexibility: "semi",
    heatMax: 65,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "easy",
    weight: "normal",
    special: [],
    pricePerKg: 25,
    toxicity: "low",
    useCases: "Decorative and light functional parts needing a bit more toughness than regular PLA.",
    pros: "Improved toughness vs PLA, still easy to print, nice surface finish.",
    cons: "Still limited heat resistance, not ideal for high-load functional parts.",
    nozzle: "205–220°C",
    bed: "50–60°C",
    speed: "200–300 mm/s",
    adhesion: "None or light glue if needed.",
    enclosure: "open_ok"
  },

  {
    id: "pla_matte",
    name: "PLA Matte",
    category: "standard",
    strength: "medium",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "easy",
    weight: "normal",
    special: [],
    pricePerKg: 27,
    toxicity: "low",
    useCases: "Cosmetic parts where surface reflections should be minimal.",
    pros: "Matte finish hides layer lines well, prints like PLA.",
    cons: "Slightly weaker than standard PLA, similar low heat resistance.",
    nozzle: "200–215°C",
    bed: "50–60°C",
    speed: "180–260 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "pla_silk",
    name: "PLA Silk",
    category: "standard",
    strength: "low",
    flexibility: "rigid",
    heatMax: 55,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "easy",
    weight: "normal",
    special: [],
    pricePerKg: 30,
    toxicity: "low",
    useCases: "Very shiny aesthetic parts, trophies, awards, cosplay accessories.",
    pros: "High gloss, mirror-like finish, hides layer lines visually.",
    cons: "Weaker interlayer adhesion, more brittle, low heat resistance.",
    nozzle: "205–225°C",
    bed: "50–60°C",
    speed: "160–240 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "pla_tough",
    name: "Tough PLA",
    category: "standard",
    strength: "high",
    flexibility: "semi",
    heatMax: 65,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "easy",
    weight: "normal",
    special: [],
    pricePerKg: 30,
    toxicity: "low",
    useCases: "Functional prototypes and jigs requiring more impact resistance than PLA.",
    pros: "Higher impact resistance, less brittle than standard PLA.",
    cons: "Still limited heat resistance, not a full PETG/ABS replacement.",
    nozzle: "210–225°C",
    bed: "50–60°C",
    speed: "180–260 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "pla_ht",
    name: "High-Temp PLA (annealable)",
    category: "standard",
    strength: "medium",
    flexibility: "semi",
    heatMax: 70,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 32,
    toxicity: "low",
    useCases: "Parts that will be annealed for higher heat resistance (jigs, fixtures).",
    pros: "Can handle higher temperatures after annealing, still PLA-like printability.",
    cons: "Requires annealing process, dimensional change during anneal.",
    nozzle: "210–230°C",
    bed: "55–65°C",
    speed: "160–240 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "pla_lw",
    name: "LW-PLA (Foaming PLA)",
    category: "standard",
    strength: "low",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "medium",
    weight: "light",
    special: [],
    pricePerKg: 40,
    toxicity: "medium",
    useCases: "RC planes, lightweight structures, cosplay when weight is critical.",
    pros: "Very low density via foaming, can reduce weight drastically.",
    cons: "Requires careful tuning, stringing, different extrusion flow at temp.",
    nozzle: "210–250°C (depending on foaming)",
    bed: "50–60°C",
    speed: "60–160 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "petg",
    name: "PETG",
    category: "standard",
    strength: "high",
    flexibility: "semi",
    heatMax: 80,
    outdoor: "good",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 25,
    toxicity: "medium",
    useCases: "Brackets, enclosures, light mechanical and outdoor parts, RC accessories.",
    pros: "Tough, good layer adhesion, more heat and impact resistant than PLA, decent outdoor performance.",
    cons: "Strings/oozes, can have weaker overhangs, likes to pick up moisture.",
    nozzle: "230–250°C",
    bed: "70–85°C",
    speed: "150–220 mm/s",
    adhesion: "Glue stick or mild adhesion recommended.",
    enclosure: "open_ok"
  },

  {
    id: "petg_matte",
    name: "PETG Matte",
    category: "standard",
    strength: "high",
    flexibility: "semi",
    heatMax: 80,
    outdoor: "good",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 30,
    toxicity: "medium",
    useCases: "Functional parts needing matte finish to hide wear and fingerprints.",
    pros: "Tough like PETG with matte look, hides surface defects better.",
    cons: "Similar stringing to PETG, slightly trickier to dial in.",
    nozzle: "235–255°C",
    bed: "70–85°C",
    speed: "140–220 mm/s",
    adhesion: "Glue / textured plate.",
    enclosure: "open_ok"
  },

  {
    id: "pctg",
    name: "PCTG",
    category: "standard",
    strength: "high",
    flexibility: "semi",
    heatMax: 80,
    outdoor: "good",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 30,
    toxicity: "medium",
    useCases: "PETG alternative when you want a bit more toughness and dimensional stability.",
    pros: "Tough and impact-resistant, often less stringy than PETG, good clarity in some grades.",
    cons: "Still more demanding than PLA, needs good cooling tuning, can be sensitive to moisture.",
    nozzle: "235–255°C",
    bed: "70–85°C",
    speed: "150–220 mm/s",
    adhesion: "Glue or textured plate; brim recommended for tall parts.",
    enclosure: "open_ok"
  },

  {
    id: "petg_transparent",
    name: "PETG Transparent",
    category: "standard",
    strength: "high",
    flexibility: "semi",
    heatMax: 80,
    outdoor: "good",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 28,
    toxicity: "medium",
    useCases: "Light pipes, covers, parts where translucency is desired.",
    pros: "Good clarity when tuned, tough and functional.",
    cons: "Printing artifacts show easily, needs careful cooling and layer settings.",
    nozzle: "235–255°C",
    bed: "70–85°C",
    speed: "120–200 mm/s",
    adhesion: "Glue/textured plate.",
    enclosure: "open_ok"
  },

  // =========================
  // ENGINEERING / STRUCTURAL
  // =========================

  {
    id: "abs",
    name: "ABS",
    category: "engineering",
    strength: "high",
    flexibility: "semi",
    heatMax: 95,
    outdoor: "poor",
    chemical: "medium",
    difficulty: "hard",
    weight: "normal",
    special: [],
    pricePerKg: 25,
    toxicity: "high",
    useCases: "Mechanical parts, enclosures, car interior parts, things needing more heat resistance than PETG/PLA.",
    pros: "Tough, good impact resistance, higher heat resistance, can be acetone-smoothed.",
    cons: "Warps easily, cracks without enclosure, strong fumes, poor UV resistance.",
    nozzle: "235–255°C",
    bed: "100–110°C",
    speed: "120–200 mm/s",
    adhesion: "ABS slurry/juice, glue, or PEI in an enclosure.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "abs_plus",
    name: "ABS+",
    category: "engineering",
    strength: "high",
    flexibility: "semi",
    heatMax: 95,
    outdoor: "poor",
    chemical: "medium",
    difficulty: "hard",
    weight: "normal",
    special: [],
    pricePerKg: 28,
    toxicity: "high",
    useCases: "ABS-style parts with slightly easier printing and better crack resistance.",
    pros: "Easier to print than pure ABS, less cracking, good toughness.",
    cons: "Still warps, still fume-heavy, not UV stable.",
    nozzle: "235–255°C",
    bed: "100–110°C",
    speed: "120–200 mm/s",
    adhesion: "Glue/ABS slurry, enclosure strongly recommended.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "abs_esd",
    name: "ABS ESD",
    category: "engineering",
    strength: "high",
    flexibility: "semi",
    heatMax: 95,
    outdoor: "poor",
    chemical: "medium",
    difficulty: "hard",
    weight: "normal",
    special: ["esd"],
    pricePerKg: 60,
    toxicity: "high",
    useCases: "Electronics tooling and enclosures where ESD control is needed.",
    pros: "ESD-safe behavior, ABS mechanical properties.",
    cons: "Fume-heavy, warping, more expensive, properties vary by brand.",
    nozzle: "240–260°C",
    bed: "100–110°C",
    speed: "100–180 mm/s",
    adhesion: "Enclosure + ABS-style bed prep.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "asa",
    name: "ASA",
    category: "engineering",
    strength: "high",
    flexibility: "semi",
    heatMax: 100,
    outdoor: "excellent",
    chemical: "medium",
    difficulty: "hard",
    weight: "normal",
    special: [],
    pricePerKg: 30,
    toxicity: "high",
    useCases: "Outdoor mounts, car exterior parts, camera mounts, anything UV exposed.",
    pros: "UV stable, good strength and heat resistance, better outdoor performance than ABS.",
    cons: "Needs enclosure, can warp, noticeable fumes.",
    nozzle: "240–260°C",
    bed: "90–110°C",
    speed: "120–200 mm/s",
    adhesion: "Glue or ASA/ABS slurry, enclosure strongly recommended.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "asa_cf",
    name: "ASA-CF",
    category: "engineering",
    strength: "very_high",
    flexibility: "rigid",
    heatMax: 105,
    outdoor: "excellent",
    chemical: "medium",
    difficulty: "hard",
    weight: "normal",
    special: ["cf"],
    pricePerKg: 55,
    toxicity: "high",
    useCases: "Stiff outdoor brackets and mounts, automotive exterior, drone mounts.",
    pros: "Stiff, strong, UV-stable, nice matte finish.",
    cons: "Abrasive, needs hardened nozzle, warping and fumes, expensive.",
    nozzle: "250–270°C",
    bed: "90–110°C",
    speed: "80–160 mm/s",
    adhesion: "Strong bed adhesion and enclosure required.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "pc",
    name: "Polycarbonate (PC)",
    category: "engineering",
    strength: "very_high",
    flexibility: "semi",
    heatMax: 115,
    outdoor: "medium",
    chemical: "medium",
    difficulty: "hard",
    weight: "normal",
    special: [],
    pricePerKg: 40,
    toxicity: "high",
    useCases: "High-strength brackets, RC arms near motors, high-load and moderate heat parts.",
    pros: "Very strong and tough, high heat resistance, good impact resistance.",
    cons: "Difficult to print, needs high temps and enclosure, warps, sensitive to moisture.",
    nozzle: "260–290°C",
    bed: "100–120°C",
    speed: "80–160 mm/s",
    adhesion: "Special PC adhesives or textured plate; enclosure required.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "pc_blend",
    name: "PC Blend (PC-ABS / PC-PBT etc.)",
    category: "engineering",
    strength: "very_high",
    flexibility: "semi",
    heatMax: 115,
    outdoor: "medium",
    chemical: "medium",
    difficulty: "hard",
    weight: "normal",
    special: [],
    pricePerKg: 45,
    toxicity: "high",
    useCases: "High-strength functional parts where full PC is tricky but needed properties are similar.",
    pros: "Easier than pure PC, strong and heat resistant, good for demanding mechanical parts.",
    cons: "Still needs enclosure and high temps, fumes, moisture-sensitive.",
    nozzle: "255–280°C",
    bed: "100–115°C",
    speed: "80–160 mm/s",
    adhesion: "Strong adhesion system and enclosure recommended.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "pc_cf",
    name: "PC-CF",
    category: "engineering",
    strength: "max",
    flexibility: "rigid",
    heatMax: 120,
    outdoor: "medium",
    chemical: "medium",
    difficulty: "hard",
    weight: "normal",
    special: ["cf"],
    pricePerKg: 70,
    toxicity: "high",
    useCases: "Extremely stiff high-temp parts, FPV arms, motor mounts, jigs.",
    pros: "Very high stiffness and strength, high heat resistance.",
    cons: "Abrasive, needs hardened nozzle, enclosure, moisture management, expensive.",
    nozzle: "270–300°C",
    bed: "100–120°C",
    speed: "60–140 mm/s",
    adhesion: "Strong bed and enclosure required.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "petg_cf",
    name: "PETG-CF",
    category: "engineering",
    strength: "very_high",
    flexibility: "rigid",
    heatMax: 80,
    outdoor: "good",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: ["cf"],
    pricePerKg: 45,
    toxicity: "medium",
    useCases: "Stiff structural parts, drone frames, brackets that need rigidity and low flex.",
    pros: "Stiffer and stronger than PETG, lower warp than ABS, nice matte finish.",
    cons: "Abrasive (needs hardened nozzle), more brittle than plain PETG, more expensive.",
    nozzle: "240–260°C",
    bed: "70–85°C",
    speed: "80–180 mm/s",
    adhesion: "Glue or textured plate; good bed needed.",
    enclosure: "open_ok"
  },

  {
    id: "pla_cf",
    name: "PLA-CF",
    category: "engineering",
    strength: "high",
    flexibility: "rigid",
    heatMax: 65,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "medium",
    weight: "normal",
    special: ["cf"],
    pricePerKg: 40,
    toxicity: "medium",
    useCases: "Rigid, dimensionally stable parts that need stiffness and nice matte finish.",
    pros: "Easy(ish) to print for a CF material, very stiff, beautiful surface.",
    cons: "Abrasive (hardened nozzle), lower impact toughness, low heat resistance like PLA.",
    nozzle: "210–230°C",
    bed: "50–60°C",
    speed: "120–220 mm/s",
    adhesion: "Usually good on textured plates; light glue if needed.",
    enclosure: "open_ok"
  },

  {
    id: "nylon_pa6",
    name: "Nylon PA6",
    category: "engineering",
    strength: "very_high",
    flexibility: "semi",
    heatMax: 110,
    outdoor: "medium",
    chemical: "good",
    difficulty: "hard",
    weight: "normal",
    special: [],
    pricePerKg: 50,
    toxicity: "high",
    useCases: "High-strength mechanical parts, gears, bushings, hinges, drive components.",
    pros: "Very tough, good wear resistance, good chemical resistance, good heat resistance.",
    cons: "Moisture magnet (must be dried), warps, needs enclosure/hot chamber, can be tricky on beds.",
    nozzle: "250–270°C",
    bed: "70–90°C",
    speed: "80–160 mm/s",
    adhesion: "Special nylon sheets, glue, or Garolite; enclosure recommended.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "nylon_pa12",
    name: "Nylon PA12",
    category: "engineering",
    strength: "high",
    flexibility: "semi",
    heatMax: 105,
    outdoor: "medium",
    chemical: "good",
    difficulty: "hard",
    weight: "normal",
    special: [],
    pricePerKg: 55,
    toxicity: "high",
    useCases: "Functional parts with good impact and fatigue resistance; slightly easier than PA6.",
    pros: "Lower water uptake than PA6, still tough and functional.",
    cons: "Still moisture-sensitive, needs careful printing and adhesion control.",
    nozzle: "245–265°C",
    bed: "70–90°C",
    speed: "80–160 mm/s",
    adhesion: "Garolite/nylon bed surface, glue, enclosure recommended.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "pa11",
    name: "Nylon PA11",
    category: "engineering",
    strength: "high",
    flexibility: "semi",
    heatMax: 105,
    outdoor: "good",
    chemical: "good",
    difficulty: "hard",
    weight: "normal",
    special: [],
    pricePerKg: 60,
    toxicity: "high",
    useCases: "Durable parts with good impact and abrasion resistance, often in SLS but some FFF grades exist.",
    pros: "Tough, good fatigue and impact resistance, better environmental resistance.",
    cons: "Moisture-sensitive, not as common in FFF, pricier.",
    nozzle: "245–265°C",
    bed: "70–90°C",
    speed: "80–160 mm/s",
    adhesion: "Garolite or specialized surface, enclosure recommended.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "nylon_cf",
    name: "Nylon-CF",
    category: "engineering",
    strength: "max",
    flexibility: "rigid",
    heatMax: 120,
    outdoor: "good",
    chemical: "good",
    difficulty: "hard",
    weight: "normal",
    special: ["cf"],
    pricePerKg: 70,
    toxicity: "high",
    useCases: "Top-tier structural parts, drone arms near motors, FPV mounts, fixtures, jigs.",
    pros: "Extremely stiff and strong, excellent mechanical performance and heat resistance.",
    cons: "Very abrasive (hardened nozzle mandatory), moisture-sensitive, needs enclosure and careful tuning.",
    nozzle: "260–285°C",
    bed: "80–100°C",
    speed: "60–150 mm/s",
    adhesion: "Garolite / specialized bed; enclosure and dry filament required.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "pa_gf",
    name: "Nylon Glass-Filled (PA-GF)",
    category: "engineering",
    strength: "max",
    flexibility: "rigid",
    heatMax: 120,
    outdoor: "good",
    chemical: "good",
    difficulty: "hard",
    weight: "normal",
    special: ["gf"],
    pricePerKg: 70,
    toxicity: "high",
    useCases: "Very rigid, load-bearing components, brackets, fixtures where stiffness is critical.",
    pros: "Very stiff and strong, good heat and chemical resistance.",
    cons: "Abrasive (hardened nozzle), warping, moisture-sensitive, demanding print environment.",
    nozzle: "260–285°C",
    bed: "80–100°C",
    speed: "60–150 mm/s",
    adhesion: "Special surfaces and enclosure; filament must be dry.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "pa_ht",
    name: "High-Temp Nylon (PA-HT)",
    category: "engineering",
    strength: "max",
    flexibility: "semi",
    heatMax: 135,
    outdoor: "good",
    chemical: "good",
    difficulty: "hard",
    weight: "normal",
    special: [],
    pricePerKg: 80,
    toxicity: "high",
    useCases: "High-temperature mechanical applications where standard nylon softens.",
    pros: "Higher heat deflection, retains strength at elevated temps.",
    cons: "Requires high nozzle temps, enclosure, extreme drying.",
    nozzle: "270–290°C",
    bed: "90–110°C",
    speed: "60–140 mm/s",
    adhesion: "Garolite / engineered surfaces, enclosed printer.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "pp",
    name: "Polypropylene (PP)",
    category: "engineering",
    strength: "medium",
    flexibility: "semi",
    heatMax: 95,
    outdoor: "good",
    chemical: "excellent",
    difficulty: "hard",
    weight: "light",
    special: [],
    pricePerKg: 35,
    toxicity: "medium",
    useCases: "Living hinges, chemical containers, parts needing chemical and fatigue resistance.",
    pros: "Excellent chemical resistance, low density (lightweight), good fatigue resistance.",
    cons: "Very poor bed adhesion without special build plates, warps, semi-flexible.",
    nozzle: "230–250°C",
    bed: "80–100°C",
    speed: "80–180 mm/s",
    adhesion: "Special PP build plates or PP tape; enclosure recommended.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "pp_gf",
    name: "PP Glass-Filled",
    category: "engineering",
    strength: "high",
    flexibility: "rigid",
    heatMax: 100,
    outdoor: "good",
    chemical: "excellent",
    difficulty: "hard",
    weight: "light",
    special: ["gf"],
    pricePerKg: 45,
    toxicity: "medium",
    useCases: "Stiffer PP parts with chemical and fatigue resistance.",
    pros: "Improved stiffness over plain PP, retains chemical resistance.",
    cons: "Abrasive, bed adhesion and warping still difficult.",
    nozzle: "240–260°C",
    bed: "80–100°C",
    speed: "60–150 mm/s",
    adhesion: "Special PP surfaces, enclosure recommended.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "hdpe",
    name: "HDPE",
    category: "engineering",
    strength: "medium",
    flexibility: "semi",
    heatMax: 80,
    outdoor: "good",
    chemical: "excellent",
    difficulty: "extreme",
    weight: "light",
    special: [],
    pricePerKg: 40,
    toxicity: "medium",
    useCases: "Very niche; chemical containers, floats, experimental parts where HDPE is specifically needed.",
    pros: "Excellent chemical resistance, low density, tough in bulk.",
    cons: "Extremely difficult to print, massive warping, poor bed adhesion, not widely supported.",
    nozzle: "230–260°C",
    bed: "80–110°C",
    speed: "60–120 mm/s",
    adhesion: "Special surfaces; even then, very challenging.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "pei_ultem",
    name: "PEI (Ultem)",
    category: "engineering",
    strength: "max",
    flexibility: "rigid",
    heatMax: 160,
    outdoor: "good",
    chemical: "good",
    difficulty: "extreme",
    weight: "normal",
    special: [],
    pricePerKg: 150,
    toxicity: "very_high",
    useCases: "Industrial only; high-temp environments, aerospace and under-hood components.",
    pros: "Very high heat resistance, very strong, industrial performance.",
    cons: "Requires very high temps and heated chamber, expensive, serious ventilation required.",
    nozzle: "360–390°C",
    bed: "130–160°C",
    speed: "40–100 mm/s",
    adhesion: "Special industrial machines; not hobby friendly.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "peek",
    name: "PEEK",
    category: "engineering",
    strength: "max",
    flexibility: "rigid",
    heatMax: 260,
    outdoor: "good",
    chemical: "excellent",
    difficulty: "extreme",
    weight: "normal",
    special: [],
    pricePerKg: 250,
    toxicity: "very_high",
    useCases: "High-end industrial/aerospace; rarely practical for hobby printing.",
    pros: "Incredible mechanical and thermal performance, chemical resistance.",
    cons: "Requires >400°C nozzle, ~150°C chamber, extremely expensive, safety concerns.",
    nozzle: "380–420°C",
    bed: "130–160°C",
    speed: "30–80 mm/s",
    adhesion: "Industrial-grade setup only.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "pps",
    name: "PPS",
    category: "engineering",
    strength: "high",
    flexibility: "rigid",
    heatMax: 200,
    outdoor: "good",
    chemical: "excellent",
    difficulty: "extreme",
    weight: "normal",
    special: [],
    pricePerKg: 180,
    toxicity: "very_high",
    useCases: "Industrial chem/heat resistant components.",
    pros: "Excellent chemical and thermal resistance.",
    cons: "Very demanding hardware, high temps, expensive.",
    nozzle: "360–390°C",
    bed: "120–150°C",
    speed: "30–80 mm/s",
    adhesion: "Industrial-grade equipment recommended.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "ppsu",
    name: "PPSU",
    category: "engineering",
    strength: "high",
    flexibility: "rigid",
    heatMax: 220,
    outdoor: "good",
    chemical: "excellent",
    difficulty: "extreme",
    weight: "normal",
    special: [],
    pricePerKg: 200,
    toxicity: "very_high",
    useCases: "High-temp, chemically aggressive environments in industrial use.",
    pros: "Outstanding heat and chemical resistance.",
    cons: "Industrial-only, very high processing temps, expensive.",
    nozzle: "360–400°C",
    bed: "120–150°C",
    speed: "30–80 mm/s",
    adhesion: "Industrial equipment recommended.",
    enclosure: "enclosure_recommended"
  },

  // =========================
  // FLEXIBLE
  // =========================

  {
    id: "tpu_95",
    name: "TPU 95A",
    category: "flexible",
    strength: "medium",
    flexibility: "flexible",
    heatMax: 60,
    outdoor: "good",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 30,
    toxicity: "medium",
    useCases: "Phone cases, vibration dampers, tires, gaskets, flexible couplers.",
    pros: "Flexible, durable, good impact and abrasion resistance.",
    cons: "Stringy, prefers slower speeds, can jam in Bowden setups.",
    nozzle: "215–235°C",
    bed: "40–60°C",
    speed: "40–80 mm/s",
    adhesion: "Usually good; light glue if needed.",
    enclosure: "open_ok"
  },

  {
    id: "tpu_85",
    name: "TPU 85A",
    category: "flexible",
    strength: "medium",
    flexibility: "flexible",
    heatMax: 60,
    outdoor: "good",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 35,
    toxicity: "medium",
    useCases: "Very soft flexible parts, seals, shock absorbers, soft grip surfaces.",
    pros: "Very flexible and elastic, excellent impact absorption.",
    cons: "More difficult to print than 95A, prefers very slow speeds and tuned extrusion path.",
    nozzle: "210–230°C",
    bed: "40–60°C",
    speed: "20–50 mm/s",
    adhesion: "Usually strong; avoid over-squish.",
    enclosure: "open_ok"
  },

  {
    id: "tpu_98",
    name: "TPU 98A",
    category: "flexible",
    strength: "high",
    flexibility: "flexible",
    heatMax: 70,
    outdoor: "good",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 32,
    toxicity: "medium",
    useCases: "Slightly firmer flexible parts, protective covers, wear pads.",
    pros: "Easier to print than very soft TPUs, still flexible.",
    cons: "Not as soft as 85A, still slower than rigid filaments.",
    nozzle: "220–240°C",
    bed: "40–60°C",
    speed: "40–90 mm/s",
    adhesion: "Typically easy.",
    enclosure: "open_ok"
  },

  {
    id: "tpe",
    name: "TPE",
    category: "flexible",
    strength: "medium",
    flexibility: "flexible",
    heatMax: 60,
    outdoor: "medium",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 35,
    toxicity: "medium",
    useCases: "Generic rubber-like parts, grips, pads, seals.",
    pros: "Soft, rubbery feel, good for grips and pads.",
    cons: "Can be very stringy and slow to print, material behavior varies by brand.",
    nozzle: "210–230°C",
    bed: "40–60°C",
    speed: "20–60 mm/s",
    adhesion: "Usually good on standard plates.",
    enclosure: "open_ok"
  },

  {
    id: "tpc",
    name: "TPC (Co-polyester flexible)",
    category: "flexible",
    strength: "medium",
    flexibility: "flexible",
    heatMax: 70,
    outdoor: "good",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 40,
    toxicity: "medium",
    useCases: "Flexible parts that need better heat resistance than basic TPU.",
    pros: "Higher temp capability than some TPUs, good flexibility.",
    cons: "Stringing, slower print speeds, less common.",
    nozzle: "220–240°C",
    bed: "50–60°C",
    speed: "30–70 mm/s",
    adhesion: "Similar to PETG/TPU.",
    enclosure: "open_ok"
  },

  // =========================
  // SUPPORT / DISSOLVABLE
  // =========================

  {
    id: "pva",
    name: "PVA",
    category: "support",
    strength: "low",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 60,
    toxicity: "medium",
    useCases: "Water-soluble support for PLA/low-temp materials.",
    pros: "Fully water-soluble, great for complex supports and internal cavities.",
    cons: "Very moisture sensitive, expensive, tuned settings needed with main material.",
    nozzle: "200–220°C",
    bed: "50–60°C",
    speed: "60–120 mm/s",
    adhesion: "Typically on top of main material; keep filament very dry.",
    enclosure: "open_ok"
  },

  {
    id: "bvoh",
    name: "BVOH",
    category: "support",
    strength: "low",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 75,
    toxicity: "medium",
    useCases: "Premium water-soluble support, usually better printing than PVA.",
    pros: "Dissolves faster and cleaner than plain PVA, good for complex supports.",
    cons: "Very moisture sensitive, expensive, storage critical.",
    nozzle: "200–220°C",
    bed: "50–60°C",
    speed: "60–120 mm/s",
    adhesion: "Used with main material; dry filament required.",
    enclosure: "open_ok"
  },

  {
    id: "hips",
    name: "HIPS",
    category: "support",
    strength: "medium",
    flexibility: "rigid",
    heatMax: 90,
    outdoor: "poor",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 30,
    toxicity: "high",
    useCases: "Breakaway or limonene-dissolvable support for ABS/ASA.",
    pros: "Dissolves in d-limonene, prints similarly to ABS.",
    cons: "Needs limonene for full dissolve, fumes and warping similar to ABS.",
    nozzle: "230–250°C",
    bed: "90–110°C",
    speed: "100–180 mm/s",
    adhesion: "Prints on same surfaces as ABS/ASA.",
    enclosure: "enclosure_recommended"
  },

  {
    id: "breakaway_pla",
    name: "Breakaway Support (PLA-based)",
    category: "support",
    strength: "low",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "easy",
    weight: "normal",
    special: [],
    pricePerKg: 30,
    toxicity: "low",
    useCases: "Supports for PLA where quick manual removal is acceptable.",
    pros: "No chemicals required, prints like PLA.",
    cons: "Leaves some marks, not suitable for impossible-to-reach cavities.",
    nozzle: "200–215°C",
    bed: "50–60°C",
    speed: "180–260 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "breakaway_petg",
    name: "Breakaway Support (PETG-based)",
    category: "support",
    strength: "low",
    flexibility: "rigid",
    heatMax: 80,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "medium",
    weight: "normal",
    special: [],
    pricePerKg: 35,
    toxicity: "medium",
    useCases: "Supports for PETG and similar temperature materials.",
    pros: "No chemicals, compatible with higher temps than PLA supports.",
    cons: "Breakaway marks, tuning interface layers is important.",
    nozzle: "230–245°C",
    bed: "70–85°C",
    speed: "120–200 mm/s",
    adhesion: "Similar to PETG.",
    enclosure: "open_ok"
  },

  // =========================
  // SPECIAL EFFECT / AESTHETIC
  // =========================

  {
    id: "pla_wood",
    name: "PLA Wood-Fill",
    category: "special",
    strength: "low",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "easy",
    weight: "normal",
    special: ["wood"],
    pricePerKg: 35,
    toxicity: "low",
    useCases: "Props, models, decorative items with wood-like look and feel.",
    pros: "Wood-like appearance and texture, can be sanded and stained.",
    cons: "Weaker than standard PLA, clogs small nozzles, needs larger nozzle and lower speeds.",
    nozzle: "200–220°C (≥0.4–0.6 mm nozzle recommended)",
    bed: "50–60°C",
    speed: "60–140 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "pla_glow",
    name: "Glow-in-the-Dark PLA",
    category: "special",
    strength: "medium",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "easy",
    weight: "normal",
    special: ["glow"],
    pricePerKg: 35,
    toxicity: "medium",
    useCases: "Glow props, gaming pieces, night markers, novelty parts.",
    pros: "Glows in the dark, easy like PLA.",
    cons: "Abrasive glow pigment (use hardened nozzle), can be brittle, glow intensity depends on pigment.",
    nozzle: "205–220°C",
    bed: "50–60°C",
    speed: "180–260 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "pla_metal_fill",
    name: "Metal-Filled PLA",
    category: "special",
    strength: "medium",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "medium",
    weight: "heavy",
    special: ["metal-look"],
    pricePerKg: 50,
    toxicity: "medium",
    useCases: "Props and models with metallic weight and appearance (bronze, copper, etc.).",
    pros: "Heavy feel, can be polished, realistic metallic appearance.",
    cons: "Abrasive (hardened nozzle recommended), brittle, stringy, expensive.",
    nozzle: "200–220°C",
    bed: "50–60°C",
    speed: "60–140 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "pla_marble",
    name: "PLA Marble",
    category: "special",
    strength: "medium",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "easy",
    weight: "normal",
    special: [],
    pricePerKg: 30,
    toxicity: "low",
    useCases: "Statues, decorative objects, cosplay, terrain.",
    pros: "Marble-like speckled look, hides layer lines.",
    cons: "Slightly more brittle than plain PLA, cosmetic only.",
    nozzle: "205–220°C",
    bed: "50–60°C",
    speed: "180–260 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "pla_rainbow",
    name: "PLA Rainbow",
    category: "special",
    strength: "medium",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "easy",
    weight: "normal",
    special: [],
    pricePerKg: 32,
    toxicity: "low",
    useCases: "Large decorative prints where gradient color is desired.",
    pros: "Color gradient on spool, good for vases and big models.",
    cons: "Color change length dependent on part size, properties like PLA.",
    nozzle: "205–220°C",
    bed: "50–60°C",
    speed: "180–260 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "conductive_pla",
    name: "Conductive PLA",
    category: "special",
    strength: "low",
    flexibility: "rigid",
    heatMax: 50,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "medium",
    weight: "normal",
    special: ["conductive"],
    pricePerKg: 80,
    toxicity: "medium",
    useCases: "Low-current circuits, touch sensors, experimental electronics.",
    pros: "Electrically conductive paths possible in printed parts.",
    cons: "High resistance (not for power), weaker mechanically, expensive.",
    nozzle: "210–230°C",
    bed: "50–60°C",
    speed: "40–120 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  },

  {
    id: "esd_filament",
    name: "ESD-Safe Filament",
    category: "special",
    strength: "medium",
    flexibility: "rigid",
    heatMax: 80,
    outdoor: "medium",
    chemical: "medium",
    difficulty: "medium",
    weight: "normal",
    special: ["esd"],
    pricePerKg: 70,
    toxicity: "medium",
    useCases: "Electronics enclosures that must not build static charge.",
    pros: "ESD-safe surface properties, good for protecting electronics.",
    cons: "More expensive, properties vary by base polymer (PLA/PETG/ABS-based).",
    nozzle: "230–260°C (depending on base polymer)",
    bed: "60–90°C",
    speed: "80–180 mm/s",
    adhesion: "As per the base polymer type.",
    enclosure: "open_ok"
  },

  {
    id: "magnetic_filament",
    name: "Magnetic Filament",
    category: "special",
    strength: "low",
    flexibility: "rigid",
    heatMax: 60,
    outdoor: "poor",
    chemical: "poor",
    difficulty: "medium",
    weight: "heavy",
    special: ["magnetic"],
    pricePerKg: 60,
    toxicity: "medium",
    useCases: "Novelty magnets, sensor mounts, small fixtures.",
    pros: "Can attract magnets and show magnetic effects.",
    cons: "Not strongly magnetic, abrasive, usually weaker mechanically.",
    nozzle: "210–230°C",
    bed: "50–60°C",
    speed: "60–140 mm/s",
    adhesion: "Similar to PLA.",
    enclosure: "open_ok"
  }
];
